/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.records;


import com.blusmart_dev.database.tables.ChargerDetails;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChargerDetailsRecord extends UpdatableRecordImpl<ChargerDetailsRecord> implements Record13<UInteger, String, BigDecimal, BigDecimal, String, Byte, Long, Long, UInteger, UInteger, String, String, String> {

    private static final long serialVersionUID = -869125188;

    /**
     * Setter for <code>blusmartDevDb.charger_details.id</code>.
     */
    public ChargerDetailsRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.charger_location</code>.
     */
    public ChargerDetailsRecord setChargerLocation(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.charger_location</code>.
     */
    public String getChargerLocation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.charger_lat</code>.
     */
    public ChargerDetailsRecord setChargerLat(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.charger_lat</code>.
     */
    public BigDecimal getChargerLat() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.charger_long</code>.
     */
    public ChargerDetailsRecord setChargerLong(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.charger_long</code>.
     */
    public BigDecimal getChargerLong() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.no_of_guns</code>.
     */
    public ChargerDetailsRecord setNoOfGuns(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.no_of_guns</code>.
     */
    public String getNoOfGuns() {
        return (String) get(4);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.is_active</code>.
     */
    public ChargerDetailsRecord setIsActive(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.created_timestamp</code>.
     */
    public ChargerDetailsRecord setCreatedTimestamp(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.created_timestamp</code>.
     */
    public Long getCreatedTimestamp() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.last_updated_timestamp</code>.
     */
    public ChargerDetailsRecord setLastUpdatedTimestamp(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.last_updated_timestamp</code>.
     */
    public Long getLastUpdatedTimestamp() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.created_by</code>.
     */
    public ChargerDetailsRecord setCreatedBy(UInteger value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.created_by</code>.
     */
    public UInteger getCreatedBy() {
        return (UInteger) get(8);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.last_updated_by</code>.
     */
    public ChargerDetailsRecord setLastUpdatedBy(UInteger value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.last_updated_by</code>.
     */
    public UInteger getLastUpdatedBy() {
        return (UInteger) get(9);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.owner</code>.
     */
    public ChargerDetailsRecord setOwner(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.owner</code>.
     */
    public String getOwner() {
        return (String) get(10);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.owner_url</code>.
     */
    public ChargerDetailsRecord setOwnerUrl(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.owner_url</code>.
     */
    public String getOwnerUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>blusmartDevDb.charger_details.app_link</code>.
     */
    public ChargerDetailsRecord setAppLink(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.charger_details.app_link</code>.
     */
    public String getAppLink() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<UInteger, String, BigDecimal, BigDecimal, String, Byte, Long, Long, UInteger, UInteger, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<UInteger, String, BigDecimal, BigDecimal, String, Byte, Long, Long, UInteger, UInteger, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return ChargerDetails.CHARGER_DETAILS.ID;
    }

    @Override
    public Field<String> field2() {
        return ChargerDetails.CHARGER_DETAILS.CHARGER_LOCATION;
    }

    @Override
    public Field<BigDecimal> field3() {
        return ChargerDetails.CHARGER_DETAILS.CHARGER_LAT;
    }

    @Override
    public Field<BigDecimal> field4() {
        return ChargerDetails.CHARGER_DETAILS.CHARGER_LONG;
    }

    @Override
    public Field<String> field5() {
        return ChargerDetails.CHARGER_DETAILS.NO_OF_GUNS;
    }

    @Override
    public Field<Byte> field6() {
        return ChargerDetails.CHARGER_DETAILS.IS_ACTIVE;
    }

    @Override
    public Field<Long> field7() {
        return ChargerDetails.CHARGER_DETAILS.CREATED_TIMESTAMP;
    }

    @Override
    public Field<Long> field8() {
        return ChargerDetails.CHARGER_DETAILS.LAST_UPDATED_TIMESTAMP;
    }

    @Override
    public Field<UInteger> field9() {
        return ChargerDetails.CHARGER_DETAILS.CREATED_BY;
    }

    @Override
    public Field<UInteger> field10() {
        return ChargerDetails.CHARGER_DETAILS.LAST_UPDATED_BY;
    }

    @Override
    public Field<String> field11() {
        return ChargerDetails.CHARGER_DETAILS.OWNER;
    }

    @Override
    public Field<String> field12() {
        return ChargerDetails.CHARGER_DETAILS.OWNER_URL;
    }

    @Override
    public Field<String> field13() {
        return ChargerDetails.CHARGER_DETAILS.APP_LINK;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getChargerLocation();
    }

    @Override
    public BigDecimal component3() {
        return getChargerLat();
    }

    @Override
    public BigDecimal component4() {
        return getChargerLong();
    }

    @Override
    public String component5() {
        return getNoOfGuns();
    }

    @Override
    public Byte component6() {
        return getIsActive();
    }

    @Override
    public Long component7() {
        return getCreatedTimestamp();
    }

    @Override
    public Long component8() {
        return getLastUpdatedTimestamp();
    }

    @Override
    public UInteger component9() {
        return getCreatedBy();
    }

    @Override
    public UInteger component10() {
        return getLastUpdatedBy();
    }

    @Override
    public String component11() {
        return getOwner();
    }

    @Override
    public String component12() {
        return getOwnerUrl();
    }

    @Override
    public String component13() {
        return getAppLink();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getChargerLocation();
    }

    @Override
    public BigDecimal value3() {
        return getChargerLat();
    }

    @Override
    public BigDecimal value4() {
        return getChargerLong();
    }

    @Override
    public String value5() {
        return getNoOfGuns();
    }

    @Override
    public Byte value6() {
        return getIsActive();
    }

    @Override
    public Long value7() {
        return getCreatedTimestamp();
    }

    @Override
    public Long value8() {
        return getLastUpdatedTimestamp();
    }

    @Override
    public UInteger value9() {
        return getCreatedBy();
    }

    @Override
    public UInteger value10() {
        return getLastUpdatedBy();
    }

    @Override
    public String value11() {
        return getOwner();
    }

    @Override
    public String value12() {
        return getOwnerUrl();
    }

    @Override
    public String value13() {
        return getAppLink();
    }

    @Override
    public ChargerDetailsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value2(String value) {
        setChargerLocation(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value3(BigDecimal value) {
        setChargerLat(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value4(BigDecimal value) {
        setChargerLong(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value5(String value) {
        setNoOfGuns(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value6(Byte value) {
        setIsActive(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value7(Long value) {
        setCreatedTimestamp(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value8(Long value) {
        setLastUpdatedTimestamp(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value9(UInteger value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value10(UInteger value) {
        setLastUpdatedBy(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value11(String value) {
        setOwner(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value12(String value) {
        setOwnerUrl(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord value13(String value) {
        setAppLink(value);
        return this;
    }

    @Override
    public ChargerDetailsRecord values(UInteger value1, String value2, BigDecimal value3, BigDecimal value4, String value5, Byte value6, Long value7, Long value8, UInteger value9, UInteger value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChargerDetailsRecord
     */
    public ChargerDetailsRecord() {
        super(ChargerDetails.CHARGER_DETAILS);
    }

    /**
     * Create a detached, initialised ChargerDetailsRecord
     */
    public ChargerDetailsRecord(UInteger id, String chargerLocation, BigDecimal chargerLat, BigDecimal chargerLong, String noOfGuns, Byte isActive, Long createdTimestamp, Long lastUpdatedTimestamp, UInteger createdBy, UInteger lastUpdatedBy, String owner, String ownerUrl, String appLink) {
        super(ChargerDetails.CHARGER_DETAILS);

        set(0, id);
        set(1, chargerLocation);
        set(2, chargerLat);
        set(3, chargerLong);
        set(4, noOfGuns);
        set(5, isActive);
        set(6, createdTimestamp);
        set(7, lastUpdatedTimestamp);
        set(8, createdBy);
        set(9, lastUpdatedBy);
        set(10, owner);
        set(11, ownerUrl);
        set(12, appLink);
    }
}
