/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.records;


import com.blusmart_dev.database.tables.Events;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> implements Record15<UInteger, UInteger, Integer, Integer, Integer, String, String, String, String, String, Byte, Long, Long, UInteger, UInteger> {

    private static final long serialVersionUID = -435203481;

    /**
     * Setter for <code>blusmartDevDb.events.id</code>.
     */
    public EventsRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>blusmartDevDb.events.driver_id</code>.
     */
    public EventsRecord setDriverId(UInteger value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.driver_id</code>.
     */
    public UInteger getDriverId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>blusmartDevDb.events.ride_id</code>.
     */
    public EventsRecord setRideId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.ride_id</code>.
     */
    public Integer getRideId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>blusmartDevDb.events.rider_id</code>.
     */
    public EventsRecord setRiderId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.rider_id</code>.
     */
    public Integer getRiderId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>blusmartDevDb.events.ride_request_id</code>.
     */
    public EventsRecord setRideRequestId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.ride_request_id</code>.
     */
    public Integer getRideRequestId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>blusmartDevDb.events.vehicle_number</code>.
     */
    public EventsRecord setVehicleNumber(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.vehicle_number</code>.
     */
    public String getVehicleNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>blusmartDevDb.events.value</code>.
     */
    public EventsRecord setValue(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.value</code>.
     */
    public String getValue() {
        return (String) get(6);
    }

    /**
     * Setter for <code>blusmartDevDb.events.type</code>.
     */
    public EventsRecord setType(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.type</code>.
     */
    public String getType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>blusmartDevDb.events.unit</code>.
     */
    public EventsRecord setUnit(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.unit</code>.
     */
    public String getUnit() {
        return (String) get(8);
    }

    /**
     * Setter for <code>blusmartDevDb.events.data</code>.
     */
    public EventsRecord setData(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.data</code>.
     */
    public String getData() {
        return (String) get(9);
    }

    /**
     * Setter for <code>blusmartDevDb.events.is_active</code>.
     */
    public EventsRecord setIsActive(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>blusmartDevDb.events.created_timestamp</code>.
     */
    public EventsRecord setCreatedTimestamp(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.created_timestamp</code>.
     */
    public Long getCreatedTimestamp() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>blusmartDevDb.events.last_updated_timestamp</code>.
     */
    public EventsRecord setLastUpdatedTimestamp(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.last_updated_timestamp</code>.
     */
    public Long getLastUpdatedTimestamp() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>blusmartDevDb.events.created_by</code>.
     */
    public EventsRecord setCreatedBy(UInteger value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.created_by</code>.
     */
    public UInteger getCreatedBy() {
        return (UInteger) get(13);
    }

    /**
     * Setter for <code>blusmartDevDb.events.last_updated_by</code>.
     */
    public EventsRecord setLastUpdatedBy(UInteger value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.events.last_updated_by</code>.
     */
    public UInteger getLastUpdatedBy() {
        return (UInteger) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<UInteger, UInteger, Integer, Integer, Integer, String, String, String, String, String, Byte, Long, Long, UInteger, UInteger> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<UInteger, UInteger, Integer, Integer, Integer, String, String, String, String, String, Byte, Long, Long, UInteger, UInteger> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Events.EVENTS.ID;
    }

    @Override
    public Field<UInteger> field2() {
        return Events.EVENTS.DRIVER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Events.EVENTS.RIDE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Events.EVENTS.RIDER_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Events.EVENTS.RIDE_REQUEST_ID;
    }

    @Override
    public Field<String> field6() {
        return Events.EVENTS.VEHICLE_NUMBER;
    }

    @Override
    public Field<String> field7() {
        return Events.EVENTS.VALUE;
    }

    @Override
    public Field<String> field8() {
        return Events.EVENTS.TYPE;
    }

    @Override
    public Field<String> field9() {
        return Events.EVENTS.UNIT;
    }

    @Override
    public Field<String> field10() {
        return Events.EVENTS.DATA;
    }

    @Override
    public Field<Byte> field11() {
        return Events.EVENTS.IS_ACTIVE;
    }

    @Override
    public Field<Long> field12() {
        return Events.EVENTS.CREATED_TIMESTAMP;
    }

    @Override
    public Field<Long> field13() {
        return Events.EVENTS.LAST_UPDATED_TIMESTAMP;
    }

    @Override
    public Field<UInteger> field14() {
        return Events.EVENTS.CREATED_BY;
    }

    @Override
    public Field<UInteger> field15() {
        return Events.EVENTS.LAST_UPDATED_BY;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public UInteger component2() {
        return getDriverId();
    }

    @Override
    public Integer component3() {
        return getRideId();
    }

    @Override
    public Integer component4() {
        return getRiderId();
    }

    @Override
    public Integer component5() {
        return getRideRequestId();
    }

    @Override
    public String component6() {
        return getVehicleNumber();
    }

    @Override
    public String component7() {
        return getValue();
    }

    @Override
    public String component8() {
        return getType();
    }

    @Override
    public String component9() {
        return getUnit();
    }

    @Override
    public String component10() {
        return getData();
    }

    @Override
    public Byte component11() {
        return getIsActive();
    }

    @Override
    public Long component12() {
        return getCreatedTimestamp();
    }

    @Override
    public Long component13() {
        return getLastUpdatedTimestamp();
    }

    @Override
    public UInteger component14() {
        return getCreatedBy();
    }

    @Override
    public UInteger component15() {
        return getLastUpdatedBy();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public UInteger value2() {
        return getDriverId();
    }

    @Override
    public Integer value3() {
        return getRideId();
    }

    @Override
    public Integer value4() {
        return getRiderId();
    }

    @Override
    public Integer value5() {
        return getRideRequestId();
    }

    @Override
    public String value6() {
        return getVehicleNumber();
    }

    @Override
    public String value7() {
        return getValue();
    }

    @Override
    public String value8() {
        return getType();
    }

    @Override
    public String value9() {
        return getUnit();
    }

    @Override
    public String value10() {
        return getData();
    }

    @Override
    public Byte value11() {
        return getIsActive();
    }

    @Override
    public Long value12() {
        return getCreatedTimestamp();
    }

    @Override
    public Long value13() {
        return getLastUpdatedTimestamp();
    }

    @Override
    public UInteger value14() {
        return getCreatedBy();
    }

    @Override
    public UInteger value15() {
        return getLastUpdatedBy();
    }

    @Override
    public EventsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public EventsRecord value2(UInteger value) {
        setDriverId(value);
        return this;
    }

    @Override
    public EventsRecord value3(Integer value) {
        setRideId(value);
        return this;
    }

    @Override
    public EventsRecord value4(Integer value) {
        setRiderId(value);
        return this;
    }

    @Override
    public EventsRecord value5(Integer value) {
        setRideRequestId(value);
        return this;
    }

    @Override
    public EventsRecord value6(String value) {
        setVehicleNumber(value);
        return this;
    }

    @Override
    public EventsRecord value7(String value) {
        setValue(value);
        return this;
    }

    @Override
    public EventsRecord value8(String value) {
        setType(value);
        return this;
    }

    @Override
    public EventsRecord value9(String value) {
        setUnit(value);
        return this;
    }

    @Override
    public EventsRecord value10(String value) {
        setData(value);
        return this;
    }

    @Override
    public EventsRecord value11(Byte value) {
        setIsActive(value);
        return this;
    }

    @Override
    public EventsRecord value12(Long value) {
        setCreatedTimestamp(value);
        return this;
    }

    @Override
    public EventsRecord value13(Long value) {
        setLastUpdatedTimestamp(value);
        return this;
    }

    @Override
    public EventsRecord value14(UInteger value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public EventsRecord value15(UInteger value) {
        setLastUpdatedBy(value);
        return this;
    }

    @Override
    public EventsRecord values(UInteger value1, UInteger value2, Integer value3, Integer value4, Integer value5, String value6, String value7, String value8, String value9, String value10, Byte value11, Long value12, Long value13, UInteger value14, UInteger value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(UInteger id, UInteger driverId, Integer rideId, Integer riderId, Integer rideRequestId, String vehicleNumber, String value, String type, String unit, String data, Byte isActive, Long createdTimestamp, Long lastUpdatedTimestamp, UInteger createdBy, UInteger lastUpdatedBy) {
        super(Events.EVENTS);

        set(0, id);
        set(1, driverId);
        set(2, rideId);
        set(3, riderId);
        set(4, rideRequestId);
        set(5, vehicleNumber);
        set(6, value);
        set(7, type);
        set(8, unit);
        set(9, data);
        set(10, isActive);
        set(11, createdTimestamp);
        set(12, lastUpdatedTimestamp);
        set(13, createdBy);
        set(14, lastUpdatedBy);
    }
}
