/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.records;


import com.blusmart_dev.database.tables.RecurringRideRequests;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecurringRideRequestsRecord extends UpdatableRecordImpl<RecurringRideRequestsRecord> {

    private static final long serialVersionUID = -1225500997;

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.id</code>.
     */
    public RecurringRideRequestsRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.rider_id</code>.
     */
    public RecurringRideRequestsRecord setRiderId(UInteger value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.rider_id</code>.
     */
    public UInteger getRiderId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.per_trip_price</code>.
     */
    public RecurringRideRequestsRecord setPerTripPrice(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.per_trip_price</code>.
     */
    public BigDecimal getPerTripPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.total_price</code>.
     */
    public RecurringRideRequestsRecord setTotalPrice(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.total_price</code>.
     */
    public BigDecimal getTotalPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.renew_count</code>.
     */
    public RecurringRideRequestsRecord setRenewCount(UInteger value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.renew_count</code>.
     */
    public UInteger getRenewCount() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.start_timestamp</code>.
     */
    public RecurringRideRequestsRecord setStartTimestamp(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.start_timestamp</code>.
     */
    public Long getStartTimestamp() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.end_timestamp</code>.
     */
    public RecurringRideRequestsRecord setEndTimestamp(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.end_timestamp</code>.
     */
    public Long getEndTimestamp() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.recurring_state</code>.
     */
    public RecurringRideRequestsRecord setRecurringState(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.recurring_state</code>.
     */
    public String getRecurringState() {
        return (String) get(7);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.configuration</code>.
     */
    public RecurringRideRequestsRecord setConfiguration(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.configuration</code>.
     */
    public String getConfiguration() {
        return (String) get(8);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.wallet_added</code>.
     */
    public RecurringRideRequestsRecord setWalletAdded(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.wallet_added</code>.
     */
    public BigDecimal getWalletAdded() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.is_active</code>.
     */
    public RecurringRideRequestsRecord setIsActive(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.created_by</code>.
     */
    public RecurringRideRequestsRecord setCreatedBy(UInteger value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.created_by</code>.
     */
    public UInteger getCreatedBy() {
        return (UInteger) get(11);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.created_at</code>.
     */
    public RecurringRideRequestsRecord setCreatedAt(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.last_updated_by</code>.
     */
    public RecurringRideRequestsRecord setLastUpdatedBy(UInteger value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.last_updated_by</code>.
     */
    public UInteger getLastUpdatedBy() {
        return (UInteger) get(13);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.last_updated_at</code>.
     */
    public RecurringRideRequestsRecord setLastUpdatedAt(Long value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.last_updated_at</code>.
     */
    public Long getLastUpdatedAt() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.note</code>.
     */
    public RecurringRideRequestsRecord setNote(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.note</code>.
     */
    public String getNote() {
        return (String) get(15);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.platform</code>.
     */
    public RecurringRideRequestsRecord setPlatform(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.platform</code>.
     */
    public String getPlatform() {
        return (String) get(16);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.estimated_distance</code>.
     */
    public RecurringRideRequestsRecord setEstimatedDistance(BigDecimal value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.estimated_distance</code>.
     */
    public BigDecimal getEstimatedDistance() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.estimated_completion_mins</code>.
     */
    public RecurringRideRequestsRecord setEstimatedCompletionMins(Integer value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.estimated_completion_mins</code>.
     */
    public Integer getEstimatedCompletionMins() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.estimated_pricing_details</code>.
     */
    public RecurringRideRequestsRecord setEstimatedPricingDetails(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.estimated_pricing_details</code>.
     */
    public String getEstimatedPricingDetails() {
        return (String) get(19);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.payment_order_id</code>.
     */
    public RecurringRideRequestsRecord setPaymentOrderId(Integer value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.payment_order_id</code>.
     */
    public Integer getPaymentOrderId() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.recurring_package_id</code>.
     */
    public RecurringRideRequestsRecord setRecurringPackageId(Integer value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.recurring_package_id</code>.
     */
    public Integer getRecurringPackageId() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.promo_code</code>.
     */
    public RecurringRideRequestsRecord setPromoCode(String value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.promo_code</code>.
     */
    public String getPromoCode() {
        return (String) get(22);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.cancellation_reason</code>.
     */
    public RecurringRideRequestsRecord setCancellationReason(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.cancellation_reason</code>.
     */
    public String getCancellationReason() {
        return (String) get(23);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.last_tried_update</code>.
     */
    public RecurringRideRequestsRecord setLastTriedUpdate(String value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.last_tried_update</code>.
     */
    public String getLastTriedUpdate() {
        return (String) get(24);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.otherFlags</code>.
     */
    public RecurringRideRequestsRecord setOtherflags(String value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.otherFlags</code>.
     */
    public String getOtherflags() {
        return (String) get(25);
    }

    /**
     * Setter for <code>blusmartDevDb.recurring_ride_requests.pause_reason</code>.
     */
    public RecurringRideRequestsRecord setPauseReason(String value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>blusmartDevDb.recurring_ride_requests.pause_reason</code>.
     */
    public String getPauseReason() {
        return (String) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecurringRideRequestsRecord
     */
    public RecurringRideRequestsRecord() {
        super(RecurringRideRequests.RECURRING_RIDE_REQUESTS);
    }

    /**
     * Create a detached, initialised RecurringRideRequestsRecord
     */
    public RecurringRideRequestsRecord(UInteger id, UInteger riderId, BigDecimal perTripPrice, BigDecimal totalPrice, UInteger renewCount, Long startTimestamp, Long endTimestamp, String recurringState, String configuration, BigDecimal walletAdded, Byte isActive, UInteger createdBy, Long createdAt, UInteger lastUpdatedBy, Long lastUpdatedAt, String note, String platform, BigDecimal estimatedDistance, Integer estimatedCompletionMins, String estimatedPricingDetails, Integer paymentOrderId, Integer recurringPackageId, String promoCode, String cancellationReason, String lastTriedUpdate, String otherflags, String pauseReason) {
        super(RecurringRideRequests.RECURRING_RIDE_REQUESTS);

        set(0, id);
        set(1, riderId);
        set(2, perTripPrice);
        set(3, totalPrice);
        set(4, renewCount);
        set(5, startTimestamp);
        set(6, endTimestamp);
        set(7, recurringState);
        set(8, configuration);
        set(9, walletAdded);
        set(10, isActive);
        set(11, createdBy);
        set(12, createdAt);
        set(13, lastUpdatedBy);
        set(14, lastUpdatedAt);
        set(15, note);
        set(16, platform);
        set(17, estimatedDistance);
        set(18, estimatedCompletionMins);
        set(19, estimatedPricingDetails);
        set(20, paymentOrderId);
        set(21, recurringPackageId);
        set(22, promoCode);
        set(23, cancellationReason);
        set(24, lastTriedUpdate);
        set(25, otherflags);
        set(26, pauseReason);
    }
}
