/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables;


import com.blusmart_dev.database.Blusmartdevdb;
import com.blusmart_dev.database.Keys;
import com.blusmart_dev.database.tables.records.DriverLeaveBalanceAudRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverLeaveBalanceAud extends TableImpl<DriverLeaveBalanceAudRecord> {

    private static final long serialVersionUID = 1549821837;

    /**
     * The reference instance of <code>blusmartDevDb.driver_leave_balance_aud</code>
     */
    public static final DriverLeaveBalanceAud DRIVER_LEAVE_BALANCE_AUD = new DriverLeaveBalanceAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DriverLeaveBalanceAudRecord> getRecordType() {
        return DriverLeaveBalanceAudRecord.class;
    }

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.aud_id</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, UInteger> AUD_ID = createField(DSL.name("aud_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.id</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, UInteger> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.driver_id</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, UInteger> DRIVER_ID = createField(DSL.name("driver_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.hour_count</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, BigDecimal> HOUR_COUNT = createField(DSL.name("hour_count"), org.jooq.impl.SQLDataType.DECIMAL(20, 8).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.is_active</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.created_timestamp</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, Long> CREATED_TIMESTAMP = createField(DSL.name("created_timestamp"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.last_updated_timestamp</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, Long> LAST_UPDATED_TIMESTAMP = createField(DSL.name("last_updated_timestamp"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.created_by</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, UInteger> CREATED_BY = createField(DSL.name("created_by"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.last_updated_by</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, UInteger> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.month</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, UInteger> MONTH = createField(DSL.name("month"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.year</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, UInteger> YEAR = createField(DSL.name("year"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.driver_leave_balance_aud.added_hours</code>.
     */
    public final TableField<DriverLeaveBalanceAudRecord, BigDecimal> ADDED_HOURS = createField(DSL.name("added_hours"), org.jooq.impl.SQLDataType.DECIMAL(20, 8).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * Create a <code>blusmartDevDb.driver_leave_balance_aud</code> table reference
     */
    public DriverLeaveBalanceAud() {
        this(DSL.name("driver_leave_balance_aud"), null);
    }

    /**
     * Create an aliased <code>blusmartDevDb.driver_leave_balance_aud</code> table reference
     */
    public DriverLeaveBalanceAud(String alias) {
        this(DSL.name(alias), DRIVER_LEAVE_BALANCE_AUD);
    }

    /**
     * Create an aliased <code>blusmartDevDb.driver_leave_balance_aud</code> table reference
     */
    public DriverLeaveBalanceAud(Name alias) {
        this(alias, DRIVER_LEAVE_BALANCE_AUD);
    }

    private DriverLeaveBalanceAud(Name alias, Table<DriverLeaveBalanceAudRecord> aliased) {
        this(alias, aliased, null);
    }

    private DriverLeaveBalanceAud(Name alias, Table<DriverLeaveBalanceAudRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> DriverLeaveBalanceAud(Table<O> child, ForeignKey<O, DriverLeaveBalanceAudRecord> key) {
        super(child, key, DRIVER_LEAVE_BALANCE_AUD);
    }

    @Override
    public Schema getSchema() {
        return Blusmartdevdb.BLUSMARTDEVDB;
    }

    @Override
    public Identity<DriverLeaveBalanceAudRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_DRIVER_LEAVE_BALANCE_AUD;
    }

    @Override
    public UniqueKey<DriverLeaveBalanceAudRecord> getPrimaryKey() {
        return Keys.KEY_DRIVER_LEAVE_BALANCE_AUD_PRIMARY;
    }

    @Override
    public List<UniqueKey<DriverLeaveBalanceAudRecord>> getKeys() {
        return Arrays.<UniqueKey<DriverLeaveBalanceAudRecord>>asList(Keys.KEY_DRIVER_LEAVE_BALANCE_AUD_PRIMARY);
    }

    @Override
    public DriverLeaveBalanceAud as(String alias) {
        return new DriverLeaveBalanceAud(DSL.name(alias), this);
    }

    @Override
    public DriverLeaveBalanceAud as(Name alias) {
        return new DriverLeaveBalanceAud(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DriverLeaveBalanceAud rename(String name) {
        return new DriverLeaveBalanceAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DriverLeaveBalanceAud rename(Name name) {
        return new DriverLeaveBalanceAud(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<UInteger, UInteger, UInteger, BigDecimal, Byte, Long, Long, UInteger, UInteger, UInteger, UInteger, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
