/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables;


import com.blusmart_dev.database.Blusmartdevdb;
import com.blusmart_dev.database.Keys;
import com.blusmart_dev.database.tables.records.HubDataRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HubData extends TableImpl<HubDataRecord> {

    private static final long serialVersionUID = 1115632955;

    /**
     * The reference instance of <code>blusmartDevDb.hub_data</code>
     */
    public static final HubData HUB_DATA = new HubData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HubDataRecord> getRecordType() {
        return HubDataRecord.class;
    }

    /**
     * The column <code>blusmartDevDb.hub_data.id</code>.
     */
    public final TableField<HubDataRecord, UInteger> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.hubName</code>.
     */
    public final TableField<HubDataRecord, String> HUBNAME = createField(DSL.name("hubName"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.latitude</code>.
     */
    public final TableField<HubDataRecord, BigDecimal> LATITUDE = createField(DSL.name("latitude"), org.jooq.impl.SQLDataType.DECIMAL(16, 8).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.longitude</code>.
     */
    public final TableField<HubDataRecord, BigDecimal> LONGITUDE = createField(DSL.name("longitude"), org.jooq.impl.SQLDataType.DECIMAL(16, 8).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.isShiftConfigurationActive</code>.
     */
    public final TableField<HubDataRecord, Byte> ISSHIFTCONFIGURATIONACTIVE = createField(DSL.name("isShiftConfigurationActive"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.created_by</code>.
     */
    public final TableField<HubDataRecord, Integer> CREATED_BY = createField(DSL.name("created_by"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.updated_by</code>.
     */
    public final TableField<HubDataRecord, Integer> UPDATED_BY = createField(DSL.name("updated_by"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.created_at</code>.
     */
    public final TableField<HubDataRecord, Long> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.last_updated_at</code>.
     */
    public final TableField<HubDataRecord, Long> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.driverCheckinRange</code>.
     */
    public final TableField<HubDataRecord, UInteger> DRIVERCHECKINRANGE = createField(DSL.name("driverCheckinRange"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.is_active</code>.
     */
    public final TableField<HubDataRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.service_region_id</code>.
     */
    public final TableField<HubDataRecord, UInteger> SERVICE_REGION_ID = createField(DSL.name("service_region_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.other_flags</code>.
     */
    public final TableField<HubDataRecord, String> OTHER_FLAGS = createField(DSL.name("other_flags"), org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * The column <code>blusmartDevDb.hub_data.hub_incharge</code>.
     */
    public final TableField<HubDataRecord, Integer> HUB_INCHARGE = createField(DSL.name("hub_incharge"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>blusmartDevDb.hub_data</code> table reference
     */
    public HubData() {
        this(DSL.name("hub_data"), null);
    }

    /**
     * Create an aliased <code>blusmartDevDb.hub_data</code> table reference
     */
    public HubData(String alias) {
        this(DSL.name(alias), HUB_DATA);
    }

    /**
     * Create an aliased <code>blusmartDevDb.hub_data</code> table reference
     */
    public HubData(Name alias) {
        this(alias, HUB_DATA);
    }

    private HubData(Name alias, Table<HubDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private HubData(Name alias, Table<HubDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> HubData(Table<O> child, ForeignKey<O, HubDataRecord> key) {
        super(child, key, HUB_DATA);
    }

    @Override
    public Schema getSchema() {
        return Blusmartdevdb.BLUSMARTDEVDB;
    }

    @Override
    public Identity<HubDataRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_HUB_DATA;
    }

    @Override
    public UniqueKey<HubDataRecord> getPrimaryKey() {
        return Keys.KEY_HUB_DATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<HubDataRecord>> getKeys() {
        return Arrays.<UniqueKey<HubDataRecord>>asList(Keys.KEY_HUB_DATA_PRIMARY);
    }

    @Override
    public HubData as(String alias) {
        return new HubData(DSL.name(alias), this);
    }

    @Override
    public HubData as(Name alias) {
        return new HubData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HubData rename(String name) {
        return new HubData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HubData rename(Name name) {
        return new HubData(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<UInteger, String, BigDecimal, BigDecimal, Byte, Integer, Integer, Long, Long, UInteger, Byte, UInteger, String, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
