/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables;


import com.blusmart_dev.database.Blusmartdevdb;
import com.blusmart_dev.database.Keys;
import com.blusmart_dev.database.tables.records.RiderPointLevelsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RiderPointLevels extends TableImpl<RiderPointLevelsRecord> {

    private static final long serialVersionUID = -361813193;

    /**
     * The reference instance of <code>blusmartDevDb.rider_point_levels</code>
     */
    public static final RiderPointLevels RIDER_POINT_LEVELS = new RiderPointLevels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RiderPointLevelsRecord> getRecordType() {
        return RiderPointLevelsRecord.class;
    }

    /**
     * The column <code>blusmartDevDb.rider_point_levels.id</code>.
     */
    public final TableField<RiderPointLevelsRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.level_name</code>.
     */
    public final TableField<RiderPointLevelsRecord, String> LEVEL_NAME = createField(DSL.name("level_name"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.level_number</code>.
     */
    public final TableField<RiderPointLevelsRecord, Integer> LEVEL_NUMBER = createField(DSL.name("level_number"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.required_points</code>.
     */
    public final TableField<RiderPointLevelsRecord, Integer> REQUIRED_POINTS = createField(DSL.name("required_points"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.level_rewards</code>.
     */
    public final TableField<RiderPointLevelsRecord, String> LEVEL_REWARDS = createField(DSL.name("level_rewards"), org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.is_active</code>.
     */
    public final TableField<RiderPointLevelsRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.create_at</code>.
     */
    public final TableField<RiderPointLevelsRecord, Long> CREATE_AT = createField(DSL.name("create_at"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.created_by</code>.
     */
    public final TableField<RiderPointLevelsRecord, Integer> CREATED_BY = createField(DSL.name("created_by"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.last_updated_at</code>.
     */
    public final TableField<RiderPointLevelsRecord, Long> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.rider_point_levels.last_updated_by</code>.
     */
    public final TableField<RiderPointLevelsRecord, Integer> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>blusmartDevDb.rider_point_levels</code> table reference
     */
    public RiderPointLevels() {
        this(DSL.name("rider_point_levels"), null);
    }

    /**
     * Create an aliased <code>blusmartDevDb.rider_point_levels</code> table reference
     */
    public RiderPointLevels(String alias) {
        this(DSL.name(alias), RIDER_POINT_LEVELS);
    }

    /**
     * Create an aliased <code>blusmartDevDb.rider_point_levels</code> table reference
     */
    public RiderPointLevels(Name alias) {
        this(alias, RIDER_POINT_LEVELS);
    }

    private RiderPointLevels(Name alias, Table<RiderPointLevelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private RiderPointLevels(Name alias, Table<RiderPointLevelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> RiderPointLevels(Table<O> child, ForeignKey<O, RiderPointLevelsRecord> key) {
        super(child, key, RIDER_POINT_LEVELS);
    }

    @Override
    public Schema getSchema() {
        return Blusmartdevdb.BLUSMARTDEVDB;
    }

    @Override
    public Identity<RiderPointLevelsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RIDER_POINT_LEVELS;
    }

    @Override
    public UniqueKey<RiderPointLevelsRecord> getPrimaryKey() {
        return Keys.KEY_RIDER_POINT_LEVELS_PRIMARY;
    }

    @Override
    public List<UniqueKey<RiderPointLevelsRecord>> getKeys() {
        return Arrays.<UniqueKey<RiderPointLevelsRecord>>asList(Keys.KEY_RIDER_POINT_LEVELS_PRIMARY);
    }

    @Override
    public RiderPointLevels as(String alias) {
        return new RiderPointLevels(DSL.name(alias), this);
    }

    @Override
    public RiderPointLevels as(Name alias) {
        return new RiderPointLevels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RiderPointLevels rename(String name) {
        return new RiderPointLevels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RiderPointLevels rename(Name name) {
        return new RiderPointLevels(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, Integer, Integer, String, Byte, Long, Integer, Long, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
