/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables;


import com.blusmart_dev.database.Blusmartdevdb;
import com.blusmart_dev.database.Keys;
import com.blusmart_dev.database.tables.records.TagTxnHeadRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagTxnHead extends TableImpl<TagTxnHeadRecord> {

    private static final long serialVersionUID = 210227195;

    /**
     * The reference instance of <code>blusmartDevDb.tag_txn_head</code>
     */
    public static final TagTxnHead TAG_TXN_HEAD = new TagTxnHead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagTxnHeadRecord> getRecordType() {
        return TagTxnHeadRecord.class;
    }

    /**
     * The column <code>blusmartDevDb.tag_txn_head.create_timestamp</code>.
     */
    public final TableField<TagTxnHeadRecord, Long> CREATE_TIMESTAMP = createField(DSL.name("create_timestamp"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.id</code>.
     */
    public final TableField<TagTxnHeadRecord, UInteger> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.token</code>.
     */
    public final TableField<TagTxnHeadRecord, String> TOKEN = createField(DSL.name("token"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.res_code</code>.
     */
    public final TableField<TagTxnHeadRecord, Integer> RES_CODE = createField(DSL.name("res_code"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.res_msg</code>.
     */
    public final TableField<TagTxnHeadRecord, String> RES_MSG = createField(DSL.name("res_msg"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.req_id</code>.
     */
    public final TableField<TagTxnHeadRecord, String> REQ_ID = createField(DSL.name("req_id"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.entity_id</code>.
     */
    public final TableField<TagTxnHeadRecord, Integer> ENTITY_ID = createField(DSL.name("entity_id"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.txn_count</code>.
     */
    public final TableField<TagTxnHeadRecord, Integer> TXN_COUNT = createField(DSL.name("txn_count"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.from_date</code>.
     */
    public final TableField<TagTxnHeadRecord, Long> FROM_DATE = createField(DSL.name("from_date"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.tag_txn_head.to_date</code>.
     */
    public final TableField<TagTxnHeadRecord, Long> TO_DATE = createField(DSL.name("to_date"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>blusmartDevDb.tag_txn_head</code> table reference
     */
    public TagTxnHead() {
        this(DSL.name("tag_txn_head"), null);
    }

    /**
     * Create an aliased <code>blusmartDevDb.tag_txn_head</code> table reference
     */
    public TagTxnHead(String alias) {
        this(DSL.name(alias), TAG_TXN_HEAD);
    }

    /**
     * Create an aliased <code>blusmartDevDb.tag_txn_head</code> table reference
     */
    public TagTxnHead(Name alias) {
        this(alias, TAG_TXN_HEAD);
    }

    private TagTxnHead(Name alias, Table<TagTxnHeadRecord> aliased) {
        this(alias, aliased, null);
    }

    private TagTxnHead(Name alias, Table<TagTxnHeadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TagTxnHead(Table<O> child, ForeignKey<O, TagTxnHeadRecord> key) {
        super(child, key, TAG_TXN_HEAD);
    }

    @Override
    public Schema getSchema() {
        return Blusmartdevdb.BLUSMARTDEVDB;
    }

    @Override
    public Identity<TagTxnHeadRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_TAG_TXN_HEAD;
    }

    @Override
    public UniqueKey<TagTxnHeadRecord> getPrimaryKey() {
        return Keys.KEY_TAG_TXN_HEAD_PRIMARY;
    }

    @Override
    public List<UniqueKey<TagTxnHeadRecord>> getKeys() {
        return Arrays.<UniqueKey<TagTxnHeadRecord>>asList(Keys.KEY_TAG_TXN_HEAD_PRIMARY);
    }

    @Override
    public TagTxnHead as(String alias) {
        return new TagTxnHead(DSL.name(alias), this);
    }

    @Override
    public TagTxnHead as(Name alias) {
        return new TagTxnHead(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTxnHead rename(String name) {
        return new TagTxnHead(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTxnHead rename(Name name) {
        return new TagTxnHead(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, UInteger, String, Integer, String, String, Integer, Integer, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
