/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables;


import com.blusmart_dev.database.Blusmartdevdb;
import com.blusmart_dev.database.Keys;
import com.blusmart_dev.database.tables.records.VehicleActionPermissionRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleActionPermission extends TableImpl<VehicleActionPermissionRecord> {

    private static final long serialVersionUID = -1841933595;

    /**
     * The reference instance of <code>blusmartDevDb.vehicle_action_permission</code>
     */
    public static final VehicleActionPermission VEHICLE_ACTION_PERMISSION = new VehicleActionPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VehicleActionPermissionRecord> getRecordType() {
        return VehicleActionPermissionRecord.class;
    }

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.id</code>.
     */
    public final TableField<VehicleActionPermissionRecord, UInteger> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.driver_id</code>.
     */
    public final TableField<VehicleActionPermissionRecord, String> DRIVER_ID = createField(DSL.name("driver_id"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.vehicle_number</code>.
     */
    public final TableField<VehicleActionPermissionRecord, String> VEHICLE_NUMBER = createField(DSL.name("vehicle_number"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.action_on_vehicle</code>.
     */
    public final TableField<VehicleActionPermissionRecord, String> ACTION_ON_VEHICLE = createField(DSL.name("action_on_vehicle"), org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.request_state</code>.
     */
    public final TableField<VehicleActionPermissionRecord, String> REQUEST_STATE = createField(DSL.name("request_state"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.is_active</code>.
     */
    public final TableField<VehicleActionPermissionRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.created_timestamp</code>.
     */
    public final TableField<VehicleActionPermissionRecord, Long> CREATED_TIMESTAMP = createField(DSL.name("created_timestamp"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.last_updated_timestamp</code>.
     */
    public final TableField<VehicleActionPermissionRecord, Long> LAST_UPDATED_TIMESTAMP = createField(DSL.name("last_updated_timestamp"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.created_by</code>.
     */
    public final TableField<VehicleActionPermissionRecord, UInteger> CREATED_BY = createField(DSL.name("created_by"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.last_updated_by</code>.
     */
    public final TableField<VehicleActionPermissionRecord, UInteger> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>blusmartDevDb.vehicle_action_permission.phone</code>.
     */
    public final TableField<VehicleActionPermissionRecord, String> PHONE = createField(DSL.name("phone"), org.jooq.impl.SQLDataType.VARCHAR(45).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>blusmartDevDb.vehicle_action_permission</code> table reference
     */
    public VehicleActionPermission() {
        this(DSL.name("vehicle_action_permission"), null);
    }

    /**
     * Create an aliased <code>blusmartDevDb.vehicle_action_permission</code> table reference
     */
    public VehicleActionPermission(String alias) {
        this(DSL.name(alias), VEHICLE_ACTION_PERMISSION);
    }

    /**
     * Create an aliased <code>blusmartDevDb.vehicle_action_permission</code> table reference
     */
    public VehicleActionPermission(Name alias) {
        this(alias, VEHICLE_ACTION_PERMISSION);
    }

    private VehicleActionPermission(Name alias, Table<VehicleActionPermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private VehicleActionPermission(Name alias, Table<VehicleActionPermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> VehicleActionPermission(Table<O> child, ForeignKey<O, VehicleActionPermissionRecord> key) {
        super(child, key, VEHICLE_ACTION_PERMISSION);
    }

    @Override
    public Schema getSchema() {
        return Blusmartdevdb.BLUSMARTDEVDB;
    }

    @Override
    public Identity<VehicleActionPermissionRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_VEHICLE_ACTION_PERMISSION;
    }

    @Override
    public UniqueKey<VehicleActionPermissionRecord> getPrimaryKey() {
        return Keys.KEY_VEHICLE_ACTION_PERMISSION_PRIMARY;
    }

    @Override
    public List<UniqueKey<VehicleActionPermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<VehicleActionPermissionRecord>>asList(Keys.KEY_VEHICLE_ACTION_PERMISSION_PRIMARY);
    }

    @Override
    public VehicleActionPermission as(String alias) {
        return new VehicleActionPermission(DSL.name(alias), this);
    }

    @Override
    public VehicleActionPermission as(Name alias) {
        return new VehicleActionPermission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleActionPermission rename(String name) {
        return new VehicleActionPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleActionPermission rename(Name name) {
        return new VehicleActionPermission(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<UInteger, String, String, String, String, Byte, Long, Long, UInteger, UInteger, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
