/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CallLogs implements Serializable {

    private static final long serialVersionUID = 1518678709;

    private Integer id;
    private String  sid;
    private String  to;
    private String  from;
    private String  phoneNumberSid;
    private String  duration;
    private String  price;
    private String  direction;
    private String  uri;
    private Integer createdBy;
    private Integer lastUpdatedBy;
    private String  note;
    private String  answerBy;
    private Byte    record;
    private Byte    isActive;
    private Long    createdAt;
    private Long    lastUpdatedAt;
    private Long    startTime;
    private Long    endTime;
    private String  status;
    private String  callType;
    private String  recordingUrl;
    private Integer rideId;

    public CallLogs() {}

    public CallLogs(CallLogs value) {
        this.id = value.id;
        this.sid = value.sid;
        this.to = value.to;
        this.from = value.from;
        this.phoneNumberSid = value.phoneNumberSid;
        this.duration = value.duration;
        this.price = value.price;
        this.direction = value.direction;
        this.uri = value.uri;
        this.createdBy = value.createdBy;
        this.lastUpdatedBy = value.lastUpdatedBy;
        this.note = value.note;
        this.answerBy = value.answerBy;
        this.record = value.record;
        this.isActive = value.isActive;
        this.createdAt = value.createdAt;
        this.lastUpdatedAt = value.lastUpdatedAt;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.status = value.status;
        this.callType = value.callType;
        this.recordingUrl = value.recordingUrl;
        this.rideId = value.rideId;
    }

    public CallLogs(
        Integer id,
        String  sid,
        String  to,
        String  from,
        String  phoneNumberSid,
        String  duration,
        String  price,
        String  direction,
        String  uri,
        Integer createdBy,
        Integer lastUpdatedBy,
        String  note,
        String  answerBy,
        Byte    record,
        Byte    isActive,
        Long    createdAt,
        Long    lastUpdatedAt,
        Long    startTime,
        Long    endTime,
        String  status,
        String  callType,
        String  recordingUrl,
        Integer rideId
    ) {
        this.id = id;
        this.sid = sid;
        this.to = to;
        this.from = from;
        this.phoneNumberSid = phoneNumberSid;
        this.duration = duration;
        this.price = price;
        this.direction = direction;
        this.uri = uri;
        this.createdBy = createdBy;
        this.lastUpdatedBy = lastUpdatedBy;
        this.note = note;
        this.answerBy = answerBy;
        this.record = record;
        this.isActive = isActive;
        this.createdAt = createdAt;
        this.lastUpdatedAt = lastUpdatedAt;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.callType = callType;
        this.recordingUrl = recordingUrl;
        this.rideId = rideId;
    }

    public Integer getId() {
        return this.id;
    }

    public CallLogs setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getSid() {
        return this.sid;
    }

    public CallLogs setSid(String sid) {
        this.sid = sid;
        return this;
    }

    public String getTo() {
        return this.to;
    }

    public CallLogs setTo(String to) {
        this.to = to;
        return this;
    }

    public String getFrom() {
        return this.from;
    }

    public CallLogs setFrom(String from) {
        this.from = from;
        return this;
    }

    public String getPhoneNumberSid() {
        return this.phoneNumberSid;
    }

    public CallLogs setPhoneNumberSid(String phoneNumberSid) {
        this.phoneNumberSid = phoneNumberSid;
        return this;
    }

    public String getDuration() {
        return this.duration;
    }

    public CallLogs setDuration(String duration) {
        this.duration = duration;
        return this;
    }

    public String getPrice() {
        return this.price;
    }

    public CallLogs setPrice(String price) {
        this.price = price;
        return this;
    }

    public String getDirection() {
        return this.direction;
    }

    public CallLogs setDirection(String direction) {
        this.direction = direction;
        return this;
    }

    public String getUri() {
        return this.uri;
    }

    public CallLogs setUri(String uri) {
        this.uri = uri;
        return this;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public CallLogs setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    public Integer getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public CallLogs setLastUpdatedBy(Integer lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
        return this;
    }

    public String getNote() {
        return this.note;
    }

    public CallLogs setNote(String note) {
        this.note = note;
        return this;
    }

    public String getAnswerBy() {
        return this.answerBy;
    }

    public CallLogs setAnswerBy(String answerBy) {
        this.answerBy = answerBy;
        return this;
    }

    public Byte getRecord() {
        return this.record;
    }

    public CallLogs setRecord(Byte record) {
        this.record = record;
        return this;
    }

    public Byte getIsActive() {
        return this.isActive;
    }

    public CallLogs setIsActive(Byte isActive) {
        this.isActive = isActive;
        return this;
    }

    public Long getCreatedAt() {
        return this.createdAt;
    }

    public CallLogs setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Long getLastUpdatedAt() {
        return this.lastUpdatedAt;
    }

    public CallLogs setLastUpdatedAt(Long lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
        return this;
    }

    public Long getStartTime() {
        return this.startTime;
    }

    public CallLogs setStartTime(Long startTime) {
        this.startTime = startTime;
        return this;
    }

    public Long getEndTime() {
        return this.endTime;
    }

    public CallLogs setEndTime(Long endTime) {
        this.endTime = endTime;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public CallLogs setStatus(String status) {
        this.status = status;
        return this;
    }

    public String getCallType() {
        return this.callType;
    }

    public CallLogs setCallType(String callType) {
        this.callType = callType;
        return this;
    }

    public String getRecordingUrl() {
        return this.recordingUrl;
    }

    public CallLogs setRecordingUrl(String recordingUrl) {
        this.recordingUrl = recordingUrl;
        return this;
    }

    public Integer getRideId() {
        return this.rideId;
    }

    public CallLogs setRideId(Integer rideId) {
        this.rideId = rideId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CallLogs other = (CallLogs) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (sid == null) {
            if (other.sid != null)
                return false;
        }
        else if (!sid.equals(other.sid))
            return false;
        if (to == null) {
            if (other.to != null)
                return false;
        }
        else if (!to.equals(other.to))
            return false;
        if (from == null) {
            if (other.from != null)
                return false;
        }
        else if (!from.equals(other.from))
            return false;
        if (phoneNumberSid == null) {
            if (other.phoneNumberSid != null)
                return false;
        }
        else if (!phoneNumberSid.equals(other.phoneNumberSid))
            return false;
        if (duration == null) {
            if (other.duration != null)
                return false;
        }
        else if (!duration.equals(other.duration))
            return false;
        if (price == null) {
            if (other.price != null)
                return false;
        }
        else if (!price.equals(other.price))
            return false;
        if (direction == null) {
            if (other.direction != null)
                return false;
        }
        else if (!direction.equals(other.direction))
            return false;
        if (uri == null) {
            if (other.uri != null)
                return false;
        }
        else if (!uri.equals(other.uri))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (lastUpdatedBy == null) {
            if (other.lastUpdatedBy != null)
                return false;
        }
        else if (!lastUpdatedBy.equals(other.lastUpdatedBy))
            return false;
        if (note == null) {
            if (other.note != null)
                return false;
        }
        else if (!note.equals(other.note))
            return false;
        if (answerBy == null) {
            if (other.answerBy != null)
                return false;
        }
        else if (!answerBy.equals(other.answerBy))
            return false;
        if (record == null) {
            if (other.record != null)
                return false;
        }
        else if (!record.equals(other.record))
            return false;
        if (isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!isActive.equals(other.isActive))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (lastUpdatedAt == null) {
            if (other.lastUpdatedAt != null)
                return false;
        }
        else if (!lastUpdatedAt.equals(other.lastUpdatedAt))
            return false;
        if (startTime == null) {
            if (other.startTime != null)
                return false;
        }
        else if (!startTime.equals(other.startTime))
            return false;
        if (endTime == null) {
            if (other.endTime != null)
                return false;
        }
        else if (!endTime.equals(other.endTime))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (callType == null) {
            if (other.callType != null)
                return false;
        }
        else if (!callType.equals(other.callType))
            return false;
        if (recordingUrl == null) {
            if (other.recordingUrl != null)
                return false;
        }
        else if (!recordingUrl.equals(other.recordingUrl))
            return false;
        if (rideId == null) {
            if (other.rideId != null)
                return false;
        }
        else if (!rideId.equals(other.rideId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.sid == null) ? 0 : this.sid.hashCode());
        result = prime * result + ((this.to == null) ? 0 : this.to.hashCode());
        result = prime * result + ((this.from == null) ? 0 : this.from.hashCode());
        result = prime * result + ((this.phoneNumberSid == null) ? 0 : this.phoneNumberSid.hashCode());
        result = prime * result + ((this.duration == null) ? 0 : this.duration.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.direction == null) ? 0 : this.direction.hashCode());
        result = prime * result + ((this.uri == null) ? 0 : this.uri.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastUpdatedBy == null) ? 0 : this.lastUpdatedBy.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        result = prime * result + ((this.answerBy == null) ? 0 : this.answerBy.hashCode());
        result = prime * result + ((this.record == null) ? 0 : this.record.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.lastUpdatedAt == null) ? 0 : this.lastUpdatedAt.hashCode());
        result = prime * result + ((this.startTime == null) ? 0 : this.startTime.hashCode());
        result = prime * result + ((this.endTime == null) ? 0 : this.endTime.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.callType == null) ? 0 : this.callType.hashCode());
        result = prime * result + ((this.recordingUrl == null) ? 0 : this.recordingUrl.hashCode());
        result = prime * result + ((this.rideId == null) ? 0 : this.rideId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CallLogs (");

        sb.append(id);
        sb.append(", ").append(sid);
        sb.append(", ").append(to);
        sb.append(", ").append(from);
        sb.append(", ").append(phoneNumberSid);
        sb.append(", ").append(duration);
        sb.append(", ").append(price);
        sb.append(", ").append(direction);
        sb.append(", ").append(uri);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastUpdatedBy);
        sb.append(", ").append(note);
        sb.append(", ").append(answerBy);
        sb.append(", ").append(record);
        sb.append(", ").append(isActive);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(lastUpdatedAt);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(status);
        sb.append(", ").append(callType);
        sb.append(", ").append(recordingUrl);
        sb.append(", ").append(rideId);

        sb.append(")");
        return sb.toString();
    }
}
