/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverDuty implements Serializable {

    private static final long serialVersionUID = 395469322;

    private UInteger id;
    private Integer  driverId;
    private Long     onlineTimestamp;
    private Long     offlineTimestamp;
    private Long     createdAt;
    private Long     lastUpdatedAt;
    private Long     tripStartTimestamp;
    private Long     tripEndTimestamp;
    private UInteger createdBy;
    private UInteger updatedBy;

    public DriverDuty() {}

    public DriverDuty(DriverDuty value) {
        this.id = value.id;
        this.driverId = value.driverId;
        this.onlineTimestamp = value.onlineTimestamp;
        this.offlineTimestamp = value.offlineTimestamp;
        this.createdAt = value.createdAt;
        this.lastUpdatedAt = value.lastUpdatedAt;
        this.tripStartTimestamp = value.tripStartTimestamp;
        this.tripEndTimestamp = value.tripEndTimestamp;
        this.createdBy = value.createdBy;
        this.updatedBy = value.updatedBy;
    }

    public DriverDuty(
        UInteger id,
        Integer  driverId,
        Long     onlineTimestamp,
        Long     offlineTimestamp,
        Long     createdAt,
        Long     lastUpdatedAt,
        Long     tripStartTimestamp,
        Long     tripEndTimestamp,
        UInteger createdBy,
        UInteger updatedBy
    ) {
        this.id = id;
        this.driverId = driverId;
        this.onlineTimestamp = onlineTimestamp;
        this.offlineTimestamp = offlineTimestamp;
        this.createdAt = createdAt;
        this.lastUpdatedAt = lastUpdatedAt;
        this.tripStartTimestamp = tripStartTimestamp;
        this.tripEndTimestamp = tripEndTimestamp;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }

    public UInteger getId() {
        return this.id;
    }

    public DriverDuty setId(UInteger id) {
        this.id = id;
        return this;
    }

    public Integer getDriverId() {
        return this.driverId;
    }

    public DriverDuty setDriverId(Integer driverId) {
        this.driverId = driverId;
        return this;
    }

    public Long getOnlineTimestamp() {
        return this.onlineTimestamp;
    }

    public DriverDuty setOnlineTimestamp(Long onlineTimestamp) {
        this.onlineTimestamp = onlineTimestamp;
        return this;
    }

    public Long getOfflineTimestamp() {
        return this.offlineTimestamp;
    }

    public DriverDuty setOfflineTimestamp(Long offlineTimestamp) {
        this.offlineTimestamp = offlineTimestamp;
        return this;
    }

    public Long getCreatedAt() {
        return this.createdAt;
    }

    public DriverDuty setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Long getLastUpdatedAt() {
        return this.lastUpdatedAt;
    }

    public DriverDuty setLastUpdatedAt(Long lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
        return this;
    }

    public Long getTripStartTimestamp() {
        return this.tripStartTimestamp;
    }

    public DriverDuty setTripStartTimestamp(Long tripStartTimestamp) {
        this.tripStartTimestamp = tripStartTimestamp;
        return this;
    }

    public Long getTripEndTimestamp() {
        return this.tripEndTimestamp;
    }

    public DriverDuty setTripEndTimestamp(Long tripEndTimestamp) {
        this.tripEndTimestamp = tripEndTimestamp;
        return this;
    }

    public UInteger getCreatedBy() {
        return this.createdBy;
    }

    public DriverDuty setCreatedBy(UInteger createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    public UInteger getUpdatedBy() {
        return this.updatedBy;
    }

    public DriverDuty setUpdatedBy(UInteger updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DriverDuty other = (DriverDuty) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (driverId == null) {
            if (other.driverId != null)
                return false;
        }
        else if (!driverId.equals(other.driverId))
            return false;
        if (onlineTimestamp == null) {
            if (other.onlineTimestamp != null)
                return false;
        }
        else if (!onlineTimestamp.equals(other.onlineTimestamp))
            return false;
        if (offlineTimestamp == null) {
            if (other.offlineTimestamp != null)
                return false;
        }
        else if (!offlineTimestamp.equals(other.offlineTimestamp))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (lastUpdatedAt == null) {
            if (other.lastUpdatedAt != null)
                return false;
        }
        else if (!lastUpdatedAt.equals(other.lastUpdatedAt))
            return false;
        if (tripStartTimestamp == null) {
            if (other.tripStartTimestamp != null)
                return false;
        }
        else if (!tripStartTimestamp.equals(other.tripStartTimestamp))
            return false;
        if (tripEndTimestamp == null) {
            if (other.tripEndTimestamp != null)
                return false;
        }
        else if (!tripEndTimestamp.equals(other.tripEndTimestamp))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!updatedBy.equals(other.updatedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.driverId == null) ? 0 : this.driverId.hashCode());
        result = prime * result + ((this.onlineTimestamp == null) ? 0 : this.onlineTimestamp.hashCode());
        result = prime * result + ((this.offlineTimestamp == null) ? 0 : this.offlineTimestamp.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.lastUpdatedAt == null) ? 0 : this.lastUpdatedAt.hashCode());
        result = prime * result + ((this.tripStartTimestamp == null) ? 0 : this.tripStartTimestamp.hashCode());
        result = prime * result + ((this.tripEndTimestamp == null) ? 0 : this.tripEndTimestamp.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DriverDuty (");

        sb.append(id);
        sb.append(", ").append(driverId);
        sb.append(", ").append(onlineTimestamp);
        sb.append(", ").append(offlineTimestamp);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(lastUpdatedAt);
        sb.append(", ").append(tripStartTimestamp);
        sb.append(", ").append(tripEndTimestamp);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }
}
