/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Manufactures implements Serializable {

    private static final long serialVersionUID = 826943413;

    private UInteger id;
    private String   manufactureName;
    private Byte     isActive;
    private Integer  createdBy;
    private Integer  lastUpdatedBy;
    private Long     createdAt;
    private Long     lastUpdatedAt;

    public Manufactures() {}

    public Manufactures(Manufactures value) {
        this.id = value.id;
        this.manufactureName = value.manufactureName;
        this.isActive = value.isActive;
        this.createdBy = value.createdBy;
        this.lastUpdatedBy = value.lastUpdatedBy;
        this.createdAt = value.createdAt;
        this.lastUpdatedAt = value.lastUpdatedAt;
    }

    public Manufactures(
        UInteger id,
        String   manufactureName,
        Byte     isActive,
        Integer  createdBy,
        Integer  lastUpdatedBy,
        Long     createdAt,
        Long     lastUpdatedAt
    ) {
        this.id = id;
        this.manufactureName = manufactureName;
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.lastUpdatedBy = lastUpdatedBy;
        this.createdAt = createdAt;
        this.lastUpdatedAt = lastUpdatedAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public Manufactures setId(UInteger id) {
        this.id = id;
        return this;
    }

    public String getManufactureName() {
        return this.manufactureName;
    }

    public Manufactures setManufactureName(String manufactureName) {
        this.manufactureName = manufactureName;
        return this;
    }

    public Byte getIsActive() {
        return this.isActive;
    }

    public Manufactures setIsActive(Byte isActive) {
        this.isActive = isActive;
        return this;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public Manufactures setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    public Integer getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public Manufactures setLastUpdatedBy(Integer lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
        return this;
    }

    public Long getCreatedAt() {
        return this.createdAt;
    }

    public Manufactures setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Long getLastUpdatedAt() {
        return this.lastUpdatedAt;
    }

    public Manufactures setLastUpdatedAt(Long lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Manufactures other = (Manufactures) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (manufactureName == null) {
            if (other.manufactureName != null)
                return false;
        }
        else if (!manufactureName.equals(other.manufactureName))
            return false;
        if (isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!isActive.equals(other.isActive))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (lastUpdatedBy == null) {
            if (other.lastUpdatedBy != null)
                return false;
        }
        else if (!lastUpdatedBy.equals(other.lastUpdatedBy))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (lastUpdatedAt == null) {
            if (other.lastUpdatedAt != null)
                return false;
        }
        else if (!lastUpdatedAt.equals(other.lastUpdatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.manufactureName == null) ? 0 : this.manufactureName.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastUpdatedBy == null) ? 0 : this.lastUpdatedBy.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.lastUpdatedAt == null) ? 0 : this.lastUpdatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Manufactures (");

        sb.append(id);
        sb.append(", ").append(manufactureName);
        sb.append(", ").append(isActive);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastUpdatedBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(lastUpdatedAt);

        sb.append(")");
        return sb.toString();
    }
}
