/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PricingRegion implements Serializable {

    private static final long serialVersionUID = -1330541136;

    private Integer  id;
    private String   pricingRegionName;
    private UInteger serviceRegionId;
    private UInteger boundId;
    private UInteger pricingModelId;
    private Byte     isActive;
    private Long     createdTimestamp;
    private Long     lastUpdatedTimestamp;
    private UInteger createdBy;
    private UInteger lastUpdatedBy;

    public PricingRegion() {}

    public PricingRegion(PricingRegion value) {
        this.id = value.id;
        this.pricingRegionName = value.pricingRegionName;
        this.serviceRegionId = value.serviceRegionId;
        this.boundId = value.boundId;
        this.pricingModelId = value.pricingModelId;
        this.isActive = value.isActive;
        this.createdTimestamp = value.createdTimestamp;
        this.lastUpdatedTimestamp = value.lastUpdatedTimestamp;
        this.createdBy = value.createdBy;
        this.lastUpdatedBy = value.lastUpdatedBy;
    }

    public PricingRegion(
        Integer  id,
        String   pricingRegionName,
        UInteger serviceRegionId,
        UInteger boundId,
        UInteger pricingModelId,
        Byte     isActive,
        Long     createdTimestamp,
        Long     lastUpdatedTimestamp,
        UInteger createdBy,
        UInteger lastUpdatedBy
    ) {
        this.id = id;
        this.pricingRegionName = pricingRegionName;
        this.serviceRegionId = serviceRegionId;
        this.boundId = boundId;
        this.pricingModelId = pricingModelId;
        this.isActive = isActive;
        this.createdTimestamp = createdTimestamp;
        this.lastUpdatedTimestamp = lastUpdatedTimestamp;
        this.createdBy = createdBy;
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public Integer getId() {
        return this.id;
    }

    public PricingRegion setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getPricingRegionName() {
        return this.pricingRegionName;
    }

    public PricingRegion setPricingRegionName(String pricingRegionName) {
        this.pricingRegionName = pricingRegionName;
        return this;
    }

    public UInteger getServiceRegionId() {
        return this.serviceRegionId;
    }

    public PricingRegion setServiceRegionId(UInteger serviceRegionId) {
        this.serviceRegionId = serviceRegionId;
        return this;
    }

    public UInteger getBoundId() {
        return this.boundId;
    }

    public PricingRegion setBoundId(UInteger boundId) {
        this.boundId = boundId;
        return this;
    }

    public UInteger getPricingModelId() {
        return this.pricingModelId;
    }

    public PricingRegion setPricingModelId(UInteger pricingModelId) {
        this.pricingModelId = pricingModelId;
        return this;
    }

    public Byte getIsActive() {
        return this.isActive;
    }

    public PricingRegion setIsActive(Byte isActive) {
        this.isActive = isActive;
        return this;
    }

    public Long getCreatedTimestamp() {
        return this.createdTimestamp;
    }

    public PricingRegion setCreatedTimestamp(Long createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
        return this;
    }

    public Long getLastUpdatedTimestamp() {
        return this.lastUpdatedTimestamp;
    }

    public PricingRegion setLastUpdatedTimestamp(Long lastUpdatedTimestamp) {
        this.lastUpdatedTimestamp = lastUpdatedTimestamp;
        return this;
    }

    public UInteger getCreatedBy() {
        return this.createdBy;
    }

    public PricingRegion setCreatedBy(UInteger createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    public UInteger getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public PricingRegion setLastUpdatedBy(UInteger lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PricingRegion other = (PricingRegion) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (pricingRegionName == null) {
            if (other.pricingRegionName != null)
                return false;
        }
        else if (!pricingRegionName.equals(other.pricingRegionName))
            return false;
        if (serviceRegionId == null) {
            if (other.serviceRegionId != null)
                return false;
        }
        else if (!serviceRegionId.equals(other.serviceRegionId))
            return false;
        if (boundId == null) {
            if (other.boundId != null)
                return false;
        }
        else if (!boundId.equals(other.boundId))
            return false;
        if (pricingModelId == null) {
            if (other.pricingModelId != null)
                return false;
        }
        else if (!pricingModelId.equals(other.pricingModelId))
            return false;
        if (isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!isActive.equals(other.isActive))
            return false;
        if (createdTimestamp == null) {
            if (other.createdTimestamp != null)
                return false;
        }
        else if (!createdTimestamp.equals(other.createdTimestamp))
            return false;
        if (lastUpdatedTimestamp == null) {
            if (other.lastUpdatedTimestamp != null)
                return false;
        }
        else if (!lastUpdatedTimestamp.equals(other.lastUpdatedTimestamp))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (lastUpdatedBy == null) {
            if (other.lastUpdatedBy != null)
                return false;
        }
        else if (!lastUpdatedBy.equals(other.lastUpdatedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.pricingRegionName == null) ? 0 : this.pricingRegionName.hashCode());
        result = prime * result + ((this.serviceRegionId == null) ? 0 : this.serviceRegionId.hashCode());
        result = prime * result + ((this.boundId == null) ? 0 : this.boundId.hashCode());
        result = prime * result + ((this.pricingModelId == null) ? 0 : this.pricingModelId.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.createdTimestamp == null) ? 0 : this.createdTimestamp.hashCode());
        result = prime * result + ((this.lastUpdatedTimestamp == null) ? 0 : this.lastUpdatedTimestamp.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastUpdatedBy == null) ? 0 : this.lastUpdatedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PricingRegion (");

        sb.append(id);
        sb.append(", ").append(pricingRegionName);
        sb.append(", ").append(serviceRegionId);
        sb.append(", ").append(boundId);
        sb.append(", ").append(pricingModelId);
        sb.append(", ").append(isActive);
        sb.append(", ").append(createdTimestamp);
        sb.append(", ").append(lastUpdatedTimestamp);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastUpdatedBy);

        sb.append(")");
        return sb.toString();
    }
}
