/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzPausedTriggerGrps implements Serializable {

    private static final long serialVersionUID = 1974344903;

    private String schedName;
    private String triggerGroup;

    public QrtzPausedTriggerGrps() {}

    public QrtzPausedTriggerGrps(QrtzPausedTriggerGrps value) {
        this.schedName = value.schedName;
        this.triggerGroup = value.triggerGroup;
    }

    public QrtzPausedTriggerGrps(
        String schedName,
        String triggerGroup
    ) {
        this.schedName = schedName;
        this.triggerGroup = triggerGroup;
    }

    public String getSchedName() {
        return this.schedName;
    }

    public QrtzPausedTriggerGrps setSchedName(String schedName) {
        this.schedName = schedName;
        return this;
    }

    public String getTriggerGroup() {
        return this.triggerGroup;
    }

    public QrtzPausedTriggerGrps setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final QrtzPausedTriggerGrps other = (QrtzPausedTriggerGrps) obj;
        if (schedName == null) {
            if (other.schedName != null)
                return false;
        }
        else if (!schedName.equals(other.schedName))
            return false;
        if (triggerGroup == null) {
            if (other.triggerGroup != null)
                return false;
        }
        else if (!triggerGroup.equals(other.triggerGroup))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.schedName == null) ? 0 : this.schedName.hashCode());
        result = prime * result + ((this.triggerGroup == null) ? 0 : this.triggerGroup.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QrtzPausedTriggerGrps (");

        sb.append(schedName);
        sb.append(", ").append(triggerGroup);

        sb.append(")");
        return sb.toString();
    }
}
