/*
 * This file is generated by jOOQ.
 */
package com.blusmart_dev.database.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfidTyres implements Serializable {

    private static final long serialVersionUID = -1565142556;

    private UInteger id;
    private Integer  rfidId;
    private String   tyreSide;
    private String   rssi;
    private String   epcId;
    private String   frequency;
    private Byte     isActive;
    private Long     createdTimestamp;
    private Long     lastUpdatedTimestamp;
    private UInteger createdBy;
    private UInteger lastUpdatedBy;

    public RfidTyres() {}

    public RfidTyres(RfidTyres value) {
        this.id = value.id;
        this.rfidId = value.rfidId;
        this.tyreSide = value.tyreSide;
        this.rssi = value.rssi;
        this.epcId = value.epcId;
        this.frequency = value.frequency;
        this.isActive = value.isActive;
        this.createdTimestamp = value.createdTimestamp;
        this.lastUpdatedTimestamp = value.lastUpdatedTimestamp;
        this.createdBy = value.createdBy;
        this.lastUpdatedBy = value.lastUpdatedBy;
    }

    public RfidTyres(
        UInteger id,
        Integer  rfidId,
        String   tyreSide,
        String   rssi,
        String   epcId,
        String   frequency,
        Byte     isActive,
        Long     createdTimestamp,
        Long     lastUpdatedTimestamp,
        UInteger createdBy,
        UInteger lastUpdatedBy
    ) {
        this.id = id;
        this.rfidId = rfidId;
        this.tyreSide = tyreSide;
        this.rssi = rssi;
        this.epcId = epcId;
        this.frequency = frequency;
        this.isActive = isActive;
        this.createdTimestamp = createdTimestamp;
        this.lastUpdatedTimestamp = lastUpdatedTimestamp;
        this.createdBy = createdBy;
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public UInteger getId() {
        return this.id;
    }

    public RfidTyres setId(UInteger id) {
        this.id = id;
        return this;
    }

    public Integer getRfidId() {
        return this.rfidId;
    }

    public RfidTyres setRfidId(Integer rfidId) {
        this.rfidId = rfidId;
        return this;
    }

    public String getTyreSide() {
        return this.tyreSide;
    }

    public RfidTyres setTyreSide(String tyreSide) {
        this.tyreSide = tyreSide;
        return this;
    }

    public String getRssi() {
        return this.rssi;
    }

    public RfidTyres setRssi(String rssi) {
        this.rssi = rssi;
        return this;
    }

    public String getEpcId() {
        return this.epcId;
    }

    public RfidTyres setEpcId(String epcId) {
        this.epcId = epcId;
        return this;
    }

    public String getFrequency() {
        return this.frequency;
    }

    public RfidTyres setFrequency(String frequency) {
        this.frequency = frequency;
        return this;
    }

    public Byte getIsActive() {
        return this.isActive;
    }

    public RfidTyres setIsActive(Byte isActive) {
        this.isActive = isActive;
        return this;
    }

    public Long getCreatedTimestamp() {
        return this.createdTimestamp;
    }

    public RfidTyres setCreatedTimestamp(Long createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
        return this;
    }

    public Long getLastUpdatedTimestamp() {
        return this.lastUpdatedTimestamp;
    }

    public RfidTyres setLastUpdatedTimestamp(Long lastUpdatedTimestamp) {
        this.lastUpdatedTimestamp = lastUpdatedTimestamp;
        return this;
    }

    public UInteger getCreatedBy() {
        return this.createdBy;
    }

    public RfidTyres setCreatedBy(UInteger createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    public UInteger getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public RfidTyres setLastUpdatedBy(UInteger lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RfidTyres other = (RfidTyres) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (rfidId == null) {
            if (other.rfidId != null)
                return false;
        }
        else if (!rfidId.equals(other.rfidId))
            return false;
        if (tyreSide == null) {
            if (other.tyreSide != null)
                return false;
        }
        else if (!tyreSide.equals(other.tyreSide))
            return false;
        if (rssi == null) {
            if (other.rssi != null)
                return false;
        }
        else if (!rssi.equals(other.rssi))
            return false;
        if (epcId == null) {
            if (other.epcId != null)
                return false;
        }
        else if (!epcId.equals(other.epcId))
            return false;
        if (frequency == null) {
            if (other.frequency != null)
                return false;
        }
        else if (!frequency.equals(other.frequency))
            return false;
        if (isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!isActive.equals(other.isActive))
            return false;
        if (createdTimestamp == null) {
            if (other.createdTimestamp != null)
                return false;
        }
        else if (!createdTimestamp.equals(other.createdTimestamp))
            return false;
        if (lastUpdatedTimestamp == null) {
            if (other.lastUpdatedTimestamp != null)
                return false;
        }
        else if (!lastUpdatedTimestamp.equals(other.lastUpdatedTimestamp))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (lastUpdatedBy == null) {
            if (other.lastUpdatedBy != null)
                return false;
        }
        else if (!lastUpdatedBy.equals(other.lastUpdatedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.rfidId == null) ? 0 : this.rfidId.hashCode());
        result = prime * result + ((this.tyreSide == null) ? 0 : this.tyreSide.hashCode());
        result = prime * result + ((this.rssi == null) ? 0 : this.rssi.hashCode());
        result = prime * result + ((this.epcId == null) ? 0 : this.epcId.hashCode());
        result = prime * result + ((this.frequency == null) ? 0 : this.frequency.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.createdTimestamp == null) ? 0 : this.createdTimestamp.hashCode());
        result = prime * result + ((this.lastUpdatedTimestamp == null) ? 0 : this.lastUpdatedTimestamp.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastUpdatedBy == null) ? 0 : this.lastUpdatedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RfidTyres (");

        sb.append(id);
        sb.append(", ").append(rfidId);
        sb.append(", ").append(tyreSide);
        sb.append(", ").append(rssi);
        sb.append(", ").append(epcId);
        sb.append(", ").append(frequency);
        sb.append(", ").append(isActive);
        sb.append(", ").append(createdTimestamp);
        sb.append(", ").append(lastUpdatedTimestamp);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastUpdatedBy);

        sb.append(")");
        return sb.toString();
    }
}
